add geckoview dep to base split. fails to find mozglue
FATAL EXCEPTION: Gecko
Process: com.example.splitapk1, PID: 19847
java.lang.RuntimeException: Could not find mozglue path.
	at org.mozilla.gecko.mozglue.GeckoLoader.getLibraryPath(GeckoLoader.java:205)
	at org.mozilla.gecko.mozglue.GeckoLoader.doLoadLibrary(GeckoLoader.java:368)
	at org.mozilla.gecko.mozglue.GeckoLoader.loadMozGlue(GeckoLoader.java:388)
	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:486)

This is because gecko's libraries are stored in the
split_config.arm64-v8a.apk APK, but with isolated splits enabled the
default class loader only includes base.apk (even in the base split)