remove remote settings from base split - can no longer load JNA
Had to define a couple resource bools due to WorkManager only being in
feature split. and remove WorkManagerInitializer from manifest to
avoid startup crash.

Now we get this:
java.lang.UnsatisfiedLinkError: Native library
(com/sun/jna/android-aarch64/libjnidispatch.so) not found in resource
path (.)